version: "3.7"

services:
    pembayaranspp:
        build: .
        container_name: container-pembayaranspp
        image: image-pembayaranspp
        env_file:
            - .env
        ports:
            - 3000:3000
        depends_on:
            - postgresdb
        restart: on-failure
        networks:
            - learning

    postgresdb:
        image: postgres:latest
        restart: always
        container_name: container-postgres
        env_file:
            - .env
        environment:
            - POSTGRES_USERNAME=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASS}
            - POSTGRES_DB=${DB_NAME}
            - DATABASE_HOST=${DB_HOST}
        volumes:
            - ./data:/var/lib/postgresql/data
        ports:
            - 5432:5432
        networks:
            - learning

networks:
    learning:
        driver: bridge